---
title: "Peer Assignment  - R Markdown"
author: "Abhishek Kaul"
date: "Tuesday, March 10, 2015"
output:
  html_document:
    keep_md: yes
---

# Part 1 - Loading and preprocessing the data

```{r}
##unzip file
unzip(zipfile="activity.zip")

## Read the activity.csv file
data <- read.csv("activity.csv")

## print top rows
head(data)
```

# Part 2  : What is mean total number of steps taken per day?

```{r}
library(ggplot2)
total.steps <- tapply(data$steps, data$date, FUN=sum, na.rm=TRUE)
qplot(total.steps, xlab="total number of steps taken each day")
mean(total.steps, na.rm=TRUE)
median(total.steps, na.rm=TRUE)

```

# Part 3 : What is the average daily activity pattern?

```{r}
library(ggplot2)
avg <- aggregate(x=list(steps=data$steps), by=list(interval=data$interval),FUN=mean, na.rm=TRUE)
ggplot(data=avg, aes(x=interval, y=steps)) + geom_line() +  xlab("5-minute interval") +  ylab("average no of steps taken")
```

##On average across all the days in the dataset, the 5-minute interval contains the maximum number of steps?

```{r}
avg[which.max(avg$steps),]
```

#Part 4: Imputing missing values

```{r}
missing <- is.na(data$steps)
# How many missing
table(missing)

# Replace each missing value with the mean value of its 5-minute interval
fill.value <- function(steps, interval) {
    filled <- NA
    if (!is.na(steps))
        filled <- c(steps)
    else
        filled <- (avg[avg$interval==interval, "steps"])
    return(filled)
}
filled.data <- data
filled.data$steps <- mapply(fill.value, filled.data$steps, filled.data$interval)

total.steps <- tapply(filled.data$steps, filled.data$date, FUN=sum)
qplot(total.steps, binwidth=1000, xlab="total number of steps taken each day")
mean(total.steps)
median(total.steps)

```

# Part 5 : Are there differences in activity patterns between weekdays and weekends?

```{r}
weekday.or.weekend <- function(date) {
    day <- weekdays(date)
    if (day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
        return("weekday")
    else if (day %in% c("Saturday", "Sunday"))
        return("weekend")
    else
        stop("invalid date")
}
filled.data$date <- as.Date(filled.data$date)
filled.data$day <- sapply(filled.data$date, FUN=weekday.or.weekend)

averages <- aggregate(steps ~ interval + day, data=filled.data, mean)
ggplot(averages, aes(interval, steps)) + geom_line() + facet_grid(day ~ .) +
    xlab("5-minute interval") + ylab("Number of steps")

```
